#!/bin/bash

FILE=`realpath -s "$(cd "$(dirname "$0")" && pwd)/../index.php"`

if [ $1 == "debug" ]; then
  DEBUG="-d xdebug.remote_autostart=On"
  XDEBUG_CONFIG="idekey=PHPSTORM remote_host=127.0.0.1 remote_port=9000"
  export PHP_IDE_CONFIG="serverName=lightning"
  REQUEST=${*:2}
else
  DEBUG=""
  REQUEST=$@
fi

php -qf $FILE $DEBUG $REQUEST
