#!/bin/bash

FILE="$(dirname "${BASH_SOURCE[0]}")/../index.php"

if [ $1 == "debug" ]; then
  DEBUG="-d xdebug.profiler_enable=On"
  XDEBUG_CONFIG="idekey=PHPSTORM remote_host=127.0.0.1 remote_port=9000"
  REQUEST=$2
else
  DEBUG=""
  REQUEST=$1
fi

php -f $FILE $DEBUG $REQUEST
